#!/usr/bin/env python3

import sys

"""
Utility tool to convert XPM files generated by GROMACS to a 3-column text file.
"""

USAGE = "USAGE: xpm2txt.py -f <input xpm file> -o <output txt file> [-s <col>]\n"
USAGE += "Options:\n"
USAGE += "\t-s\t(int)\tSort output by given 1-based column (1/2/3).\n"


def parse_args(argv):
    read_input = read_output = read_sort = False
    xpm_file = out_file = None
    column_sort = None

    for arg in argv:
        if read_input:
            read_input = False
            xpm_file = arg
            continue
        if read_output:
            read_output = False
            out_file = arg
            continue
        if read_sort:
            read_sort = False
            try:
                column_sort = int(arg)
            except ValueError:
                print(USAGE)
                sys.stderr.write(f"ERROR: Invalid sort column: {arg}\n")
                sys.exit(1)
            continue

        if arg.startswith("-"):
            if arg == "-f":
                read_input = True
            elif arg == "-o":
                read_output = True
            elif arg == "-s":
                read_sort = True
            else:
                print(USAGE)
                sys.stderr.write(f"ERROR: Option not recognized: {arg}\n")
                sys.exit(1)

    if not xpm_file:
        print(USAGE)
        sys.stderr.write("ERROR: Missing input file (-f).\n")
        sys.exit(1)

    if not out_file:
        out_file = "out.txt"

    return xpm_file, out_file, column_sort


def parse_xpm(xpm_file):
    xpm_data = []
    x_axis, y_axis = [], []
    letter_to_value = {}

    with open(xpm_file, "r", encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            if line.startswith("/* x-axis"):
                x_axis = [float(v) for v in line.split()[2:-2]]

            if line.startswith("/* y-axis"):
                y_axis = [float(v) for v in line.split()[2:-2]]

            if line.startswith('"') and x_axis and y_axis:
                xpm_data.insert(0, line.strip().strip(',')[1:-1])

            if line.startswith('"') and len(line.split()) > 4:
                letter = line.split()[0][1:]
                value = float(line.split()[-2][1:-1])
                letter_to_value[letter] = value

    if not x_axis or not y_axis or not xpm_data:
        raise ValueError("Failed to parse XPM axes/data. Check input format.")

    txt_values = []
    for y_index, data_value in enumerate(xpm_data):
        y_val = y_axis[y_index]
        for x_index, x_val in enumerate(x_axis):
            key = data_value[x_index]
            if key not in letter_to_value:
                continue
            txt_values.append([x_val, y_val, letter_to_value[key]])

    return txt_values


def main():
    xpm_file, out_file, column_sort = parse_args(sys.argv[1:])
    values = parse_xpm(xpm_file)

    if column_sort is not None:
        idx = column_sort - 1
        if idx < 0 or idx > 2:
            print(USAGE)
            sys.stderr.write(f"ERROR: Invalid sort column: {column_sort}\n")
            sys.exit(1)
        values.sort(key=lambda r: r[idx])

    with open(out_file, "w", encoding="utf-8") as out:
        for x, y, z in values:
            out.write(f"{x:3.5f}\t{y:3.5f}\t{z:3.5f}\n")


if __name__ == "__main__":
    main()
